### ISSUE TITLE
accept expression-lists for Physical entities

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#19] opened 2016-04-21 23:56 UTC
> the expression-list on the right hand side should contain the identification numbers of all the elementary points that need to be grouped inside the physical point. [http://gmsh.info/doc/texinfo/gmsh.html#index-Physical-points]
> 
> the expression-list on the right hand side should contain the identification numbers of all the elementary lines that need to be grouped inside the physical line [http://gmsh.info/doc/texinfo/gmsh.html#index-Physical-lines]

Usage is widespread; e.g. https://onelab.info/svn/gmsh/trunk/tutorial/t1.geo

```
Physical Point(1) = {1,2} ;
```

I hope to propose a pull-request shortly.

**Comment by nschloe** [comment] 2016-07-02 14:33
I guess we can close here since PR #22 has been merged.

**Comment by gdmcbain** [comment] 2016-07-04 00:38
No, actually.  The comment in #22 referring to this issue was:

> This does not include the handling of expression-lists discussed in #19.

The methods `add_physical_line` and `add_physical_point` added in #17 and #22 are analogous to the older `add_physical_volume` and `add_physical_surface`.  Like them, they don't actually strictly follow the [specification](http://gmsh.info/doc/texinfo/gmsh.html#Geometry-commands) which states that the right-hand side of each of these is an [_expression-list_](http://gmsh.info/doc/texinfo/gmsh.html#Expressions), enclosed in braces and followed by a semicolon.  The specification does allow a simplification for singletons:

> Note that, in order to lighten the syntax, you can omit the braces {} enclosing an expression-list if this expression-list only contains a single item.

At present, the PyGmsh methods only provide this lightened form.  The present issue is to generalize these methods to accept the full form, with a braced expression-list on the right-hand side.

For this, I'm thinking something along the lines of:

    @staticmethod
    def expression_list(*expressions):
        return '{%s}' % ', '.join(expressions)

This is essentially the same construction already used inside many other methods of `class Geometry`; e.g. `add_bspline`, `add_compound_line`, `add_line_loop`, ... 

This can be used as:

    >>> expression_list('p1')
    '{p1}'
    >>> expression_list('p1', 'p2')
    '{p1, p2}'
    >>> points = ['p%d' % (i + 1) for i in range(2)]
    >>> points
    ['p1', 'p2']
    >>> expression_list(*points)
    '{p1, p2}'   

The second and third examples turn a Python sequence into a string, as required to be able to generate a command equivalent to the one quoted above on 22 Apr. from tutorial [t1.geo](http://gmsh.info/doc/texinfo/gmsh.html#t1_002egeo).

The first example shows that the new code also maintains support for input of singletons, though doesn't omit the braces.  I'm not sure that implementing that optional omission is too important?

Would there be interest in a pull-request implementing the above for the four `add_physical_*` functions?  If so, I suppose it should follow the style of the existing methods and in-line the generation of the expression-list rather than using a helper function like the above.

**Comment by briandrawert** [comment] 2016-11-30 21:52
Not sure if this is the same bug or not, but to get a physical surface made of multiple elementary surfaces I had to do this:
```
sl = geom.add_surface_loop(surfaces_list)
ps = geom.add_physical_surface('{'+','.join(surfaces_list)+'}')

```

**Comment by beckerrh** [comment] 2017-03-05 13:54
In addition to the above, it would be nice to be able to have integers as labels, as in the gmsh-example t1.geo:
 "
MY_LINE = 2;
Physical Line(MY_LINE) = {1,2} ;
"
It seems to me that this is for the moment not possible in PyGmsh, since the
'_new_physical_group' method always puts quotes around the label.

**Comment by nschloe** [comment] 2017-03-14 10:20
@everyone If you have a new problem, please open a new bug. We can always close that as a duplicate of another one if it turns out that way.

@beckerrh Is this really supported? I only ever see strings as `Physical` labels.

**Comment by nschloe** [comment] 2017-03-14 10:57
Lists are now supported à la
```
geom.add_physical_line([l1, l2, l3])
```

**Closed by nschloe** 2017-03-14 10:57 UTC

**Comment by beckerrh** [comment] 2017-03-20 13:17
Works fine for me ! Thanks a lot.
