### ISSUE TITLE
Error with pygmsh library

### ISSUE THREAD

**Issue by edwardramg** [nschloe/pygmsh#156] opened 2018-03-08 18:39 UTC
Good morning,
I have a problem that causes me error with the pygmsh library, at the moment of executing code for that library.
I describe the steps I followed:
Install python 3.6.4
Install pygmsh 4.1.1
Execute Gmsh version 3.0.6
charge in the IDLE 3.6.4 (64 bits) a test code:
```python
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 15 12:11:41 2018
@author: Me
"""
import pygmsh
import numpy as np
import meshio
geom = pygmsh.built_in.Geometry()
ballHole = geom.add_ball(x0=[0.5,0.5,0.5], radius=0.25, lcar=0.10,)
geom.add_box(0, 1, 0, 1, 0, 1, 0.10, holes=[ballHole.surface_loop])
points, cells, point_data, cell_data, field_data = pygmsh.helpers.generate_mesh(geom)
meshio.write('test.msh', points, cells, cell_data=cell_data) # The .msh file in gmsh format
meshio.write('test.vtu', points, cells, cell_data=cell_data) #The output file can be visualized with various tools, e.g., ParaView.
```
I run the test code
and I get the following error:
```
>>> 
 RESTART: I:\Users\mramos\OneDrive\Documentos\IMP\Manuel\Python\pygmsh_test.py 
Traceback (most recent call last):
  File "I:\Users\mramos\OneDrive\Documentos\IMP\Manuel\Python\pygmsh_test.py", line 12, in <module>
    points, cells, point_data, cell_data, field_data = pygmsh.helpers.generate_mesh(geom)
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\site-packages\pygmsh\helpers.py", line 119, in generate_mesh
    gmsh_major_version = get_gmsh_major_version(gmsh_executable)
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\site-packages\pygmsh\helpers.py", line 82, in get_gmsh_major_version
    stderr=subprocess.STDOUT
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mramos\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
>>> 
```
I appreciate your help in this regard.

best regards

**Comment by nschloe** [comment] 2018-03-08 18:44
Sounds very much like pygmsh cannot find gmsh. Do you have it installed? If yes and pygmsh just cannot find it, try the `gmsh_path` argument to `generate_mesh`.

**Comment by nschloe** [comment] 2018-03-08 18:46
Duplicate of https://github.com/nschloe/pygmsh/issues/108 and https://github.com/nschloe/pygmsh/issues/147.

**Closed by nschloe** 2018-03-08 18:46 UTC

**Comment by edwardramg** [comment] 2018-03-08 21:06
Thank you already works well, greetings.

Saludos cordiales,

Atte... 

!Mario Eduardo Ramos García

De: Nico Schlömer [mailto:notifications@github.com]
Enviado el: jueves, 8 de marzo de 2018 12:47 p. m.
Para: nschloe/pygmsh <pygmsh@noreply.github.com>
CC: Mario Eduardo Ramos Garcia <mramos@imp.mx>; Author <author@noreply.github.com>
Asunto: Re: [nschloe/pygmsh] Error with pygmsh library (#156)


Duplicate of #108<https://github.com/nschloe/pygmsh/issues/108> and #147<https://github.com/nschloe/pygmsh/issues/147>.
