### ISSUE TITLE
Extrude with lower order entities

### ISSUE THREAD

**Issue by ForeverAFalcon84** [nschloe/pygmsh#238] opened 2019-01-30 13:26 UTC
I don't know if this would be useful to anybody else, but I find there's no clean way to use Pygmesh built-in functions to complete de following Gmsh sequence that builds a cube with perfectly rectilinear tetrahedrons with a determined number of rows/layers:

`lc = 0.099;`
`Point(1) = {-0.5, -0.5, -0.5, lc};`
`Point(2) = {0.5, -0.5, -0.5, lc};`
`Line(3) = {1, 2};`
`e1[] = Extrude{0, 1, 0}{Line{3}; Layers{10};};`
`e2[] = Extrude{0, 0, 1}{Surface{e1[1]}; Layers{10};};`
`Physical Volume("internalField") = {e2[1]};`

This happens because Pygmesh extrude function does not allow lower geometrical entities to be extruded but only surfaces into volumes. (Line creation in that code could be further controlled through yet a lower extrude from P0, which again doesn't work in PyPI)

My solution was to build the raw code string list base on these lines and to use `add_raw_code` method to tell Pygmsh to do this.

Is there any way for geometry.extrude method to allow for constructions of extruded lines and surfaces through points and lines as source objects respectively? This way the extrude method will allow to set a regular layer mesh size/distribution control over lower dimensions and get more regular en better quality meshes for many cases.

The context is that I find Gmsh to produce some very poor elements 3D (practically 2D) when a high number of elements are requested for an unstructured tetrahedron mesh in a parallelepiped geometry (cylindrical as well, probably many others, even after issuing Optimize option). These are not a lot, but they break my FEM solution process for some prototype elements I build and research. For these and other similar geometries, Gmsh's layer control can be used to yield a perfectly regular tet mesh.

The aforementioned lines were actually suggested by Takuya Oshima in a Gmsh issue resolution and they work wonders.

Thanks in advance

**Comment by gdmcbain** [comment] 2019-01-30 23:44
I also just noticed that for parallelepiped geometry, one has https://github.com/nschloe/pygmsh/blob/67b776fcc22ba05722ee2808708242d24fce6925/pygmsh/built_in/geometry.py#L618 and https://github.com/nschloe/pygmsh/blob/67b776fcc22ba05722ee2808708242d24fce6925/pygmsh/opencascade/geometry.py#L62

**Comment by gdmcbain** [comment] 2019-01-30 23:56
There is actually an example of extruding a line in https://github.com/nschloe/pygmsh/blob/67b776fcc22ba05722ee2808708242d24fce6925/test/test_hex.py#L16-L18 .  The test passes here.  Does it work for you?

I stepped through it with pdb and saved the `geom.get_code()`; it closely resembles yours:
```
// This code was created by pygmsh v4.3.6.
p0 = newp;
Point(p0) = {0.0, 0.0, 0.0, 1.0};
p1 = newp;
Point(p1) = {2, 0.0, 0.0, 1.0};
l0 = newl;
Line(l0) = {p0, p1};
ex1[] = Extrude {0.0,3,0.0} {Line{l0}; Layers{3}; Recombine;};
ex2[] = Extrude {0.0,0.0,5} {Surface{ex1[1]}; Layers{5}; Recombine;};
```

**Comment by ForeverAFalcon84** [comment] 2019-01-31 13:53
Sure it does ! 

I appreciate you taking the time to clarify. At the end it was me who was not understanding the `geom.extrude` function on its entirety: I wasn't extracting back the intermediate surface entity properly since I wasn't careful about the `return top, extruded, lat` specification from the function definition.

The add_box doesn't allow me to have the layered control I have with the extrusions but a single `lcar`. So not much use for the mesh I want there...

I'm really sorry to have you bothered a bit with this. On the other hand, I understand the library better.

Have a great day !

Alex O.

**Comment by gdmcbain** [comment] 2019-01-31 19:17
You're welcome and thanks for the detailed reply.

I note that pygmsh doesn't cover Gmsh's facility to extrude the lowest order entities, points, but will mark this issue for closure and leave that till it arises.

**Comment by toothstone** [comment] 2019-03-04 17:11
Just FYI, I think this is pretty much a duplicate of #236, although I wasn't aware of line extrusion so far. Now that I'm done with my exams I will get started on the promised PR.

**Comment by nschloe** [comment] 2019-03-08 20:21
@toothstone I'll leave it up to you to close this one.

**Comment by toothstone** [comment] 2019-03-11 09:41
I think this code:
```python
import pygmsh
lc = 0.099
geom = pygmsh.built_in.geometry.Geometry()
p1 = geom.add_point([-0.5, -0.5, -0.5], lc)
p2 = geom.add_point([0.5, -0.5, -0.5], lc)
line = geom.add_line(p1, p2)
_, s, _ = geom.extrude(line, translation_axis=[0, 1, 0], num_layers=10)
_, v, _ = geom.extrude(s, translation_axis=[0, 0, 1], num_layers=10)
geom.add_physical_volume(v, "internalField")
```
is now doing exactly what @ForeverAFalcon84 asked for, the mesh is highly regular and the resulting .geo code is looking nearly exactly like the example given.

However I can't close the issue since I don't have permissions to do so^^

**Closed** 2019-03-11 09:58 UTC
