### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by SterlingButters** [nschloe/pygmsh#147] opened 2018-02-18 23:52 UTC
Running first code block example in ReadMe yields following error:

```
Traceback (most recent call last):
  File "C:/Users/Sterling Butters/PycharmProjects/Monte Carlo Neutron Transport/PyGMSH", line 31, in <module>
    points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 120, in generate_mesh
    gmsh_major_version = get_gmsh_major_version(gmsh_executable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 82, in get_gmsh_major_version
    stderr=subprocess.STDOUT
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1
```

**Comment by gdmcbain** [comment] 2018-02-19 01:58
Duplicate of #108.

Try setting the [`PATH`](https://github.com/nschloe/pygmsh/issues/108#issuecomment-347859257)) to Gmsh.

**Comment by nschloe** [comment] 2018-02-27 08:11
@gdmcbain is right. Closing.

**Closed by nschloe** 2018-02-27 08:11 UTC
