### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by kebitmatf** [nschloe/pygmsh#71] opened 2017-06-12 02:22 UTC
I tried the the test code that you posted. Importing pygmsh is fine but the: geom.extrude raised an error:
```python
geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
    )
```
```
Out[20]: (<pygmsh.dummy.Dummy at 0xb028080>, <pygmsh.dummy.Dummy at 0xb0284e0>)
```
I'm using spyder python 3.5, Windows 64bits.
Please help me to solve this issue!

**Comment by nschloe** [comment] 2017-06-12 06:50
I tried the code on three different machines and  I cannot reproduce it. The example code is also part of the integration tests. This makes it quite likely that the issue is in your local setup.

**Comment by nschloe** [comment] 2017-06-16 08:08
On second thought, is the output you're getting what you perceive as an error? Because it's not. Those are just two `Dummy` objects returned from `extrude()`, namely the top surface and the extruded volume.

I'm closing this issue, but feel free to reopen if more questions arise.

**Closed by nschloe** 2017-06-16 08:08 UTC
